const majors = [
    "Bachelor of Design in City Innovation",
    "Ancient and Medieval History",
    "Anthropology",
    "Archaeology",
    "Art History",
    "Canadian Studies",
    "Communication and Media Studies",
    "Dance",
    "Drama",
    "Earth Science",
    "East Asian Language Studies",
    "East Asian Studies",
    "Economics",
    "English",
    "Film Studies",
    "French",
    "Gender and Sexuality Studies",
    "Geography",
    "German",
    "Global Development Studies",
    "Greek and Roman Studies",
    "History",
    "International Indigenous Studies",
    "International Relations",
    "Italian Studies",
    "Language and Culture",
    "Latin American Studies",
    "Law and Society",
    "Linguistics",
    "Music",
    "Philosophy",
    "Political Science",
    "Psychology",
    "Religious Studies",
    "Russian",
    "Sociology",
    "Spanish",
    "Urban Studies",
    "Visual Studies",
    "Community Rehabilitation",
    "Bioinformatics",
    "Biomedical Sciences",
    "Health and Society",
    "Doctor of Medicine",
    "Commerce",
    "Kinesiology",
    "Leadership and Coaching",
    "Motor and Psychosocial Aspects of Movement",
    "Biomechanics",
    "Exercise and Health Physiology",
    "Law",
    "Nursing",
    "Biomedical Engineering",
    "Chemical Engineering",
    "Civil Engineering",
    "Electrical Engineering",
    "Energy Engineering",
    "Geomatics Engineering",
    "Mechanical Engineering",
    "Software Engineering",
    "Sustainable Systems Engineering",
    "Computer Science",
    "Actuarial Science",
    "Applied Chemistry",
    "Applied Mathematics",
    "Astrophysics",
    "Biochemistry",
    "Biological Sciences",
    "Cellular, Molecular and Microbial Biology",
    "Chemistry",
    "Ecology",
    "Environmental Science",
    "General Mathematics",
    "Geology",
    "Geophysics",
    "Mathematics",
    "Natural Sciences",
    "Neuroscience",
    "Physics",
    "Plant Biology",
    "Pure Mathematics",
    "Statistics",
    "Zoology",
    "Social Work",
    "Doctor of Veterinary Medicine",
    "Elementary Education",
    "Secondary Education",
  ];
  
export default majors